Repository blackmagic-debug/blackmagic, pull requests merged in 2022-06, with the labels that each got.

#215 Add 96Boards Carbon as a probe host
  src/platforms/96b_carbon/Makefile.inc
  src/platforms/96b_carbon/Readme.md
  src/platforms/96b_carbon/platform.c
  src/platforms/96b_carbon/platform.h
  src/platforms/96b_carbon/usbdfu.c
  src/platforms/stm32/96b_carbon.ld
Labels: New Host Board, BMP Firmware

#954 rtt to usb serial
  UsingRTT.md
  driver/99-blackmagic.rules
  src/Makefile
  src/command.c
  src/gdb_main.c
  src/include/rtt.h
  src/include/rtt_if.h
  src/platforms/hosted/platform.c
  src/platforms/hosted/rtt_if.c
  src/platforms/stm32/rtt_if.c
  src/platforms/stm32/usbuart.c
  src/platforms/tm4c/usbuart.c
  src/rtt.c
Labels: Enhancement

#1018 update include/version.h only when content changes
  src/Makefile
Labels: Enhancement

#1024 Formatting and printf format string fixes for the ch32f1 support
  src/target/ch32f1.c
Labels: Bug, BMD App

#1015 add shell.nix
  shell.nix
Labels: Enhancement

#431 Implement watchpoints on Cortex-A
  src/target/cortexa.c
Labels: Enhancement

#1028 Complete the version string migration from 5e3cade, fixing build for HOSTED_BMP_ONLY=1
  src/platforms/hosted/bmp_serial.c
Labels: Bug, BMD App, Regression

#1014 added RTS and DTR to UART interface
  src/platforms/common/cdcacm.c
  src/platforms/swlink/platform.h
Labels: Enhancement, BMP Firmware

#1045 RP2040 updates
  src/target/rp.c
Labels: Bug, HwIssue Mitigation, BMP Firmware

#1041 STM32 bootloader serial number handling cleanup
  src/platforms/stm32/serialno.c
Labels: Bug, BMP Firmware

#1050 Fix version.h generation on BSD-like OSes
  scripts/gen-version.sh
  src/Makefile
Labels: Bug, Regression

#1051 hosted/cmsis-dap: Various CMSIS-DAP implementation correctness improvements
  src/platforms/hosted/cmsis_dap.c
Labels: BMD App

#1012 clang-format: add initial format file
  .clang-format
Labels: Enhancement

#1058 RP2040: Better detection of flash size
  src/target/rp.c
Labels: Enhancement

#1066 Fix a formatting bug that breaks, among other things, breakpoints
  src/gdb_main.c
Labels: Bug, Regression

#1067 stm32wlxx: CPU2 needs wake-up call and has unexpected PIDR4 in AP1
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/cortexm.c
  src/target/stm32l4.c
Labels: Bug

#1070 Fix a couple of bugs in Cortex-M watchpoint and register handling
  src/target/cortexm.c
Labels: Bug

#1068 Serial number regression fix
  src/platforms/stm32/serialno.c
Labels: Bug, BMP Firmware, Regression

#1075 Added a code of conduct based on the Contributors Covenant
  CODE_OF_CONDUCT.md
Labels: Enhancement, Documentation

#1017 Add idcode for GD32F303CG detection
  src/target/stm32f1.c
Labels: New Target

#1079 VSCode extension recomendations
  .vscode/extensions.json
Labels: Enhancement, Documentation

#1080 target/sam3x: saner uninitialized variable prevention
  src/target/sam3x.c
Labels: Bug

#1081 STM32F1 general cleanup and GD32E230 option write special case
  src/target/stm32f1.c
Labels: Bug

#1083 ST-Link: Fix the LED pinout on the Nucleo boards
  src/platforms/stlink/platform.h
Labels: Bug, BMP Firmware

#1084 Fix 24 digit serial numbers
  src/platforms/stm32/serialno.c
Labels: Bug, BMP Firmware, Regression

#1085 Fix: main branch CI
  .github/workflows/build-and-upload.yml
  .github/workflows/build-pr.yml
Labels: Bug, Regression

#1082 Fix build error and logic in rp.c
  src/target/rp.c
Labels: Bug, Regression
