Repository blackmagic-debug/blackmagic, pull requests merged in 2022-08, with the labels that each got.

#1155 Fix jlink vid-pid
  src/platforms/hosted/jlink.c
Labels: Bug, BMD App

#1167 target/cortexm: print t->part_id not ap->partno in unknown device warning
  src/target/cortexm.c
Labels: Bug, Regression

#1170 target/stm32h7: fix ids
  src/target/stm32h7.c
Labels: Bug, Regression

#1161 hosted/cli: Made sure the command line options structure is initialised with opt_mode = BMP_MODE_DEBUG before args parsing
  src/platforms/hosted/cli.c
Labels: Bug, BMD App

#1162 Fix: SAMD series mask
  src/target/samd.c
Labels: Bug

#1164 Fix: BMDA uses the wrong libusb
  src/platforms/hosted/Makefile.inc
Labels: Bug, BMD App

#1178 native: Enable uart on HW >=V3 when debugging.
  src/platforms/native/platform.c
Labels: Bug, BMP Firmware, NativeHardware

#1191 Fix: F072 and F3 platform documentation
  src/platforms/f072/Readme
  src/platforms/f072/Readme.md
  src/platforms/f3/Readme
  src/platforms/f3/Readme.md
Labels: Documentation

#1181 Fix: ATSAMD attach errata
  src/target/samd.c
Labels: Bug, HwIssue Mitigation

#1195 Fix: JTAG ADIv5 DPv0 detection
  src/platforms/hosted/jlink_adiv5_swdp.c
  src/platforms/hosted/stlinkv2.c
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/adiv5_jtagdp.c
  src/target/adiv5_swdp.c
Labels: Bug, Regression

#1197 gdb_main: don't print debug for vMustReplyEmpty packets
  src/gdb_main.c
Labels: Enhancement, GDB

#1206 ch32f1: Correct the debug output format string.
  src/target/ch32f1.c
Labels: Bug

#1207 rtt: Cleaned up updated and improved the RTT usage documentation.
  UsingRTT.md
  driver/README.md
Labels: BMP Firmware, Documentation

#1208 swo-docs: Converted to markdown and cleaned up a bit.
  UsingSWO
  UsingSWO.md
Labels: BMP Firmware, Documentation

#1210 Added two missing license headers in BMDA.
  src/platforms/hosted/bmp_hosted.h
  src/platforms/hosted/platform.h
Labels: Documentation

#1209 Cleanup include guards.
  src/gdb_hostio.h
  src/include/command.h
  src/include/crc32.h
  src/include/exception.h
  src/include/gdb_if.h
  src/include/gdb_main.h
  src/include/gdb_packet.h
  src/include/general.h
  src/include/hex_utils.h
  src/include/jtagtap.h
  src/include/morse.h
  src/include/platform_support.h
  src/include/rtt.h
  src/include/rtt_if.h
  src/include/serialno.h
  src/include/target.h
  src/include/timing.h
  src/platforms/96b_carbon/platform.h
  src/platforms/blackpillv2/platform.h
  src/platforms/common/aux_serial.h
  src/platforms/common/traceswo.h
  src/platforms/common/usb.h
  src/platforms/common/usb_descriptors.h
  src/platforms/common/usb_dfu_stub.h
  src/platforms/common/usb_serial.h
  src/platforms/f072/platform.h
  src/platforms/f3/platform.h
  src/platforms/f4discovery/platform.h
  src/platforms/hosted/bmp_hosted.h
  src/platforms/hosted/bmp_remote.h
  src/platforms/hosted/cli.h
  src/platforms/hosted/cmsis_dap.h
  src/platforms/hosted/dap.h
  src/platforms/hosted/ftdi_bmp.h
  src/platforms/hosted/jlink.h
  src/platforms/hosted/platform.h
  src/platforms/hosted/stlinkv2.h
  src/platforms/hydrabus/platform.h
  src/platforms/launchpad-icdi/platform.h
  src/platforms/native/platform.h
  src/platforms/stlink/platform.h
  src/platforms/stm32/gpio.h
  src/platforms/stm32/timing_stm32.h
  src/platforms/stm32/usbdfu.h
  src/platforms/swlink/platform.h
  src/remote.h
  src/target/adiv5.h
  src/target/cortexm.h
  src/target/flashstub/stub.h
  src/target/jtag_devs.h
  src/target/jtag_scan.h
  src/target/lpc_common.h
  src/target/semihosting.h
  src/target/sfdp.h
  src/target/sfdp_internal.h
  src/target/target_internal.h
  src/target/target_probe.h
  upgrade/bindata.h
  upgrade/dfu.h
  upgrade/stm32mem.h
Labels: Enhancement

#1214 sam4l: fix debug formatting
  src/target/sam4l.c
Labels: Bug, Regression

#1213 Fix: RTT formatting regression
  src/command.c
Labels: Bug, Regression

#1223 cortexm: fix printf format for cpuid_partno
  src/target/cortexm.c
Labels: Bug, Regression
