Repository blackmagic-debug/blackmagic, pull requests merged in 2022-10, with the labels that each got.

#1249 stm32f1xx: Fix broken vFlashErase
  src/target/stm32f1.c
Labels: Bug

#1253 Fix USART on SWIM pins for STLINK
  src/platforms/stlink/Makefile.inc
  src/platforms/stlink/platform.h
Labels: Bug

#1247 Fix: adiv5 nuisance CID warnings
  src/target/adiv5.c
Labels: Bug, Regression

#1266 fix: BMDA FTDI configuration for FT4232H
  src/platforms/hosted/ftdi_bmp.c
Labels: Bug, BMD App

#1267 stm32f1: Identify GD32F330 correctly
  src/target/stm32f1.c
Labels: Bug

#1268 rp: fix format for debug print
  src/target/rp.c
Labels: Bug, Regression

#1272 target/nrf52: stop inverting return on nrf51_cmd_read_*
  src/target/nrf51.c
Labels: Bug, Regression
