Repository blackmagic-debug/blackmagic, pull requests merged in 2022-07, with the labels that each got.

#1091 Fix several errors in the main project README
  README.md
Labels: Bug, Documentation

#1098 Fix: kinetis Flash control correctness
  src/target/kinetis.c
Labels: Bug, Regression

#1106 BMP V2.3: Fix outdated ADC reads.
  src/platforms/native/platform.c
Labels: HwIssue Mitigation, BMP Firmware, NativeHardware

#1086 Implement semihosting debug output redirection to usb-uart port.
  src/include/general.h
  src/platforms/hydrabus/platform.h
  src/platforms/launchpad-icdi/platform.h
  src/platforms/native/platform.h
  src/platforms/stlink/platform.h
  src/platforms/stm32/usbuart.c
  src/platforms/swlink/platform.h
  src/platforms/tm4c/usbuart.c
  src/target/cortexm.c
  src/target/target.c
  src/target/target_internal.h
Labels: Enhancement, BMP Firmware

#1093 Fix: target Flash buffer lifetime bounding
  src/target/target.c
Labels: Bug, BMP Firmware

#1107 stm32f4: Fix erase_mass command return error.
  src/target/stm32f4.c
Labels: Bug

#1102 efm32 cleanup
  src/target/efm32.c
Labels: Bug, HwIssue Mitigation

#1110 Add homebrew include so that libusb headers found.
  src/platforms/hosted/Makefile.inc
Labels: Bug, BMD App

#1119 misc: Added the libusb-dev BMDA to the GHA main build workflow
  .github/workflows/build-and-upload.yml
Labels: Bug, Regression

#1113 target: Implemented a command to allow erasing Flash ranges on any target
  src/target/target.c
Labels: Enhancement, BMP Firmware

#1114 Fix: Remove the BMDA `-d`/`--device` deprecation warning
  src/platforms/hosted/cli.c
Labels: Bug, BMD App, Documentation

#1127 gdb_main: Fixed a small DEBUG_GDB regression for vFlashErase and vFlashWrite debugging
  src/gdb_main.c
Labels: Bug, Regression

#1132 target: fix probing for lpc1343
  src/target/cortexm.c
Labels: Bug, Regression

#1144 fix: Use standard macros for debug message formating
  src/target/adiv5.c
Labels: Bug, Regression

#1148 Fixed compatibility issues with CH32F1 driver and other STM32F103 clones
  src/target/ch32f1.c
Labels: Bug, HwIssue Mitigation

#1135 Fix: ADIv5 AP scan early bailout
  src/target/adiv5.c
Labels: Bug, Regression

#947 Do not turn IDLE LED off when port closed and target already detached
  src/gdb_main.c
Labels: Enhancement, BMP Firmware

#1027 stm32/gdb_if: Use _WFI when nothing to do.
  src/platforms/stm32/gdb_if.c
Labels: Enhancement, User Testing Needed, BMP Firmware

#1151 Added support for AT32F403A/407/415.
  src/target/cortexm.c
  src/target/stm32f1.c
  src/target/target_probe.c
  src/target/target_probe.h
Labels: New Target
