Repository blackmagic-debug/blackmagic, pull requests merged in 2022-03, with the labels that each got.

#987 Added support for fine-grained bootloader and flash locking in samd.c
  src/target/samd.c
Labels: Enhancement

#976 sscanf cleanup in GDB Z packet handler
  src/gdb_main.c
Labels: Bug

#973 STM32F4: Move DBGMCU_handling to target specific code. Apply for F7 too.
  src/target/adiv5.c
  src/target/stm32f4.c
Labels: Bug, Regression
