Repository blackmagic-debug/blackmagic, pull requests merged in 2022-09, with the labels that each got.

#1224 rp: invert success logic in rp_flash_write
  src/target/rp.c
Labels: Bug, Regression

#1244 target/renesas: add known id for RA2A1
  src/target/renesas.c
Labels: Bug

#1217 Addition of selectable fast polling for hosted use cases
  src/gdb_main.c
  src/include/platform_support.h
  src/platforms/hosted/cli.c
  src/platforms/hosted/cli.h
  src/platforms/hosted/platform.c
Labels: Enhancement

#1242 stm32f4: fix wrong idcode when probing
  src/target/stm32f4.c
Labels: Bug, Regression

#1246 Added ST-Link udev rules
  driver/99-stlink-plugdev.rules
Labels: Enhancement

#1250 Add required quotes to st-link udev rules
  driver/99-stlink-plugdev.rules
Labels: Bug
