Repository blackmagic-debug/blackmagic, pull requests merged in 2022-11, with the labels that each got.

#1276 rtt: fix #1248, RTT for F072 (STM32F072) platform not working
  UsingRTT.md
  src/command.c
  src/include/rtt.h
  src/include/target.h
  src/rtt.c
  src/target/target.c
Labels: Bug

#1263 Fix: stm32f1 Flash routine functionality fixes
  src/target/stm32f1.c
Labels: Bug, Regression

#1220 Fix: SWD timings
  src/platforms/common/swdptap.c
Labels: Bug, BMP Firmware

#1279 rtt: cleanup
  src/command.c
  src/rtt.c
Labels: Bug

#1264 CH32F1x: More reliable chip detection, inverted function logic to be …
  src/target/ch32f1.c
Labels: Bug

#1283 stlink: set BLUEPILL compiler option if BLUEPILL environment variable set
  src/platforms/stlink/Makefile.inc
Labels: Bug

#1303 Fix: adiv5 sticky error handling
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/adiv5_jtagdp.c
Labels: Bug, HwIssue Mitigation

#1305 Fix: STM32W device IDs
  src/target/stm32l4.c
Labels: Bug, Regression

#1306 Fix: STM32F1 option bytes regression
  src/target/stm32f1.c
Labels: Bug, HwIssue Mitigation, Regression

#1309 #1302 followup
  src/rtt.c
Labels: Enhancement

#1312 Fix: RP2040 blank flash bringup
  src/target/rp.c
Labels: Bug, HwIssue Mitigation, Regression

#1311 Fix: JTAG timings
  src/platforms/common/jtagtap.c
Labels: Bug, BMP Firmware, Regression

#1313 hosted/dap: Fixed error in link reset pointer math.
  src/platforms/hosted/dap.c
Labels: Bug, BMD App, Regression

#1314 fix: USB serial DTR handling and resulting USB packet sent on the wrong endpoint regression
  src/platforms/common/usb_serial.c
Labels: Bug, BMP Firmware, Regression

#1317 crc32 fixup: missing return type change
  src/crc32.c
Labels: Bug, Regression
