Repository blackmagic-debug/blackmagic, pull requests merged in 2022-12, with the labels that each got.

#1318 stm32f1: Fixed a regression in the identification of STM32F0 parts
  src/target/stm32f1.c
Labels: Bug, Regression

#1321 Fix: not handling ERROR_SUCCESS return code from RegGetValue
  src/platforms/hosted/serial_win.c
Labels: Bug, BMD App, Regression

#1325 Fix: nrf52 probe memory exhaustion
  src/target/nrf51.c
Labels: Bug

#1326 check argc
  src/command.c
Labels: Bug

#1329 target/stm32f4: correct code used to look up part name
  src/target/stm32f4.c
Labels: Bug, Regression

#1322 Fix: udev symlinks when multiple probes are attached to one host
  driver/99-blackmagic-plugdev.rules
  driver/99-blackmagic-uucp.rules
Labels: Bug, Enhancement

#1338 target_flash: fix missing null check on target_flash_erase
  src/target/target_flash.c
Labels: Bug

#1347 Fix: Flashing from the hosted CLI on macOS/*nix
  src/platforms/hosted/cli.c
Labels: Bug, BMD App, Regression

#1350 hosted/dap: Fixed dap_jtagtap_tdi_tdo_seq() crashing when ticks is 0 and final_tms is true
  src/platforms/hosted/dap.c
Labels: Bug, BMD App
