Repository blackmagic-debug/blackmagic, pull requests merged in 2023-12, with the labels that each got.

#1702 target/flashstub: fix variable initialization in stm32f1_flash_write_…
  src/target/flashstub/lmi.c
Labels: Bug

#1701 Fix typos
  src/gdb_main.c
  src/gdb_packet.c
  src/platforms/common/blackpill-f4/README.md
  src/platforms/common/usb_serial.c
  src/platforms/hosted/bmp_libusb.c
  src/platforms/hosted/bmp_remote.c
  src/platforms/hosted/bmp_serial.c
  src/platforms/hosted/cmsis_dap.c
  src/platforms/hosted/ftdi_bmp.c
  src/platforms/hosted/jlink.c
  src/platforms/hosted/jlink_swd.c
  src/platforms/hosted/remote/protocol_v0_adiv5.c
  src/platforms/hosted/remote/protocol_v1_adiv5.c
  src/platforms/hosted/remote/protocol_v3_adiv5.c
  src/platforms/hosted/stlinkv2.c
  src/platforms/native/platform.c
  src/remote.c
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/adiv5_jtag.c
  src/target/cortexar.c
  src/target/imxrt.c
  src/target/jtag_scan.c
  src/target/lpc43xx.c
  src/target/lpc_common.c
  src/target/msp432e4.c
  src/target/riscv32.c
  src/target/riscv_debug.h
Labels: Enhancement, Documentation

#1698 Fix: Missing Cortex-A/R memory IO diagnostics
  src/target/cortexar.c
Labels: Enhancement

#1690 Fix: Speed up bus turnaround for blackpill-f4 like other platforms
  src/platforms/common/blackpill-f4/blackpill-f4.h
Labels: Enhancement, BMP Firmware, Foreign Host Board
