Repository blackmagic-debug/blackmagic, pull requests merged in 2023-07, with the labels that each got.

#1435 Fix: ORBTrace version protection
  src/platforms/hosted/cmsis_dap.c
  src/platforms/hosted/dap.h
  src/platforms/hosted/dap_jtag.c
Labels: Bug, BMD App

#1533 imxrt: ungate boot_mode even on non-hosted
  src/target/imxrt.c
Labels: Bug, BMP Firmware

#1534 imxrt: correct logic of debug guard
  src/target/imxrt.c
Labels: Bug, Regression

#1536 Fix: Increase SysTick frequency to 1kHz
  src/include/timing.h
Labels: Enhancement, BMP Firmware

#1538 Feature: Flash state tracking
  src/target/target_flash.c
  src/target/target_internal.h
Labels: Enhancement

#1539 Fix: CMSIS-DAP versioning identification
  src/platforms/hosted/cmsis_dap.c
Labels: Bug, BMD App

#1540 Feature: Identify AT32F435/437
  src/target/stm32f1.c
Labels: New Target

#1526 Fix: Refactor LPC43xx target sram detection code
  src/target/lpc43xx.c
Labels: Enhancement

#1544 Fix: ADIv5 DP init
  src/target/adiv5.c
Labels: Bug, Enhancement

#1550 platforms/f4discovery: Update README.md
  src/platforms/f4discovery/README.md
Labels: Documentation, Foreign Host Board

#1551 Fix: ST-Link v2 serial number readout
  src/platforms/hosted/bmp_libusb.c
Labels: Bug, BMD App

#1555 clang-tidy: Additions for case checking in source code
  .clang-tidy
Labels: Enhancement, CI

#1552 Fix: BMDA CMSIS-DAP v2 selection
  src/platforms/hosted/bmp_libusb.c
  src/platforms/hosted/platform.c
Labels: Bug, BMD App, Regression

#1558 hosted/bmp_libusb: Work around missing char16_t typedef in Darwin
  src/platforms/hosted/bmp_libusb.c
Labels: Bug, BMD App

#1561 hosted: Correct copyright notices
  src/platforms/hosted/bmp_libusb.c
  src/platforms/hosted/windows/ftdi.c
  src/platforms/hosted/windows/ftdi.h
Labels: BMD App, Documentation

#1560 Fix: threads-induced IDE hangups
  src/gdb_main.c
Labels: Bug, GDB, Regression

#1562 Fix: LPC43x0 Flash detection failure mishandling
  src/target/lpc43xx.c
Labels: Bug

#1563 Fix: Remote protocol packet handling organisation
  src/gdb_packet.c
Labels: Enhancement

#1572 stm32l4.c: Fix RAM size argument to some target_add_ram()
  src/target/stm32l4.c
Labels: Bug

#1571 gdb_packet: include stdbool.h
  src/include/gdb_packet.h
Labels: Bug, GDB

#1570 Fix: jlink hw version
  src/platforms/hosted/jlink.c
  src/platforms/hosted/jlink_protocol.h
Labels: Bug, BMD App

#1574 Stm32u5 support
  src/target/stm32l4.c
Labels: New Target

#1577 Fix: ADIv5 debug bringup reliability
  src/target/adiv5.c
  src/target/adiv5.h
Labels: Bug, HwIssue Mitigation
