Repository blackmagic-debug/blackmagic, pull requests merged in 2023-08, with the labels that each got.

#1578 Fix: reword vMustReplyEmpty comment
  src/gdb_main.c
Labels: Documentation

#1580 Fix: CMSIS-DAP WAIT handling
  src/platforms/hosted/dap_command.c
Labels: Bug, BMD App, Regression

#1588 Fix morse new null msg
  src/include/morse.h
  src/morse.c
Labels: Bug, BMP Firmware

#1597 Fix: enum fwd ref pedantic warning
  src/platforms/common/usb_types.h
Labels: Bug, Enhancement

#1591 Fix: char-subscripts warnings
  src/gdb_main.c
  src/morse.c
Labels: Enhancement

#1602 riscv: Check if hw reset worked, if not do a DM reset
  src/target/riscv_debug.c
Labels: Bug, HwIssue Mitigation

#1593 Fix: bad-function-cast warnings
  src/platforms/common/aux_serial.c
Labels: Bug, BMP Firmware

#1584 Fix: ADIv5 DPv0 ID Codes
  src/platforms/hosted/stlinkv2_swd.c
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/adiv5_jtag.c
  src/target/adiv5_swd.c
Labels: Bug, HwIssue Mitigation, Regression

#1604 Fix: remove dangling extern
  src/include/general.h
Labels: Enhancement

#1612 samx5x: don't assume that flash block size == flash region lock size
  src/target/samx5x.c
Labels: Bug, HwIssue Mitigation

#1610 Fix: cmsis_dap: error when writing long buffers to DAP (>59 bytes)
  src/platforms/hosted/cmsis_dap.c
  src/platforms/hosted/dap_command.c
  src/platforms/hosted/dap_command.h
Labels: Bug, BMD App, Regression

#1613 target: Add missing braces to array of struct initializers.
  src/target/imxrt.c
  src/target/stm32g0.c
Labels: Bug, Regression

#1316 Add initial nRF91 support.
  src/Makefile
  src/target/cortexm.c
  src/target/nrf91.c
  src/target/target_probe.c
  src/target/target_probe.h
Labels: New Target
