Repository blackmagic-debug/blackmagic, pull requests merged in 2023-05, with the labels that each got.

#1486 imxrt: use %u for formatting status code
  src/target/imxrt.c
Labels: Bug

#1487 github: update action/checkout tag used in lint
  .github/workflows/lint.yml
Labels: Enhancement

#1474 Unify help syntax
  src/command.c
Labels: Enhancement

#1489 Build - Fix building BMDA due to alloca being undefined.
  src/platforms/hosted/ftdi_bmp.c
Labels: Bug, BMD App

#1494 Fix: platforms/blackpill-f4: fix typo in readme
  src/platforms/common/blackpill-f4/README.md
Labels: Bug, Documentation

#1496 gd32f2xx: add support detection of GD32F2XX microcontrollers
  src/target/stm32f1.c
Labels: New Target
