Repository blackmagic-debug/blackmagic, pull requests merged in 2023-11, with the labels that each got.

#1674 Fix `monitor erase*` usage messages (UX)
  src/target/target.c
Labels: Bug, Enhancement

#1673 Fix: libusb overflow with JLink
  src/platforms/hosted/jlink.c
Labels: Bug, HwIssue Mitigation, BMD App

#1669 Fix: BMDA remote protocol writes
  src/platforms/hosted/serial_win.c
Labels: Bug, BMD App, Regression

#1681 command: Convert format-string in heapinfo
  src/command.c
Labels: Bug, Enhancement, Documentation

#1687 send initial usb cdc notification from the correct endpoint
  src/platforms/common/usb_serial.c
Labels: Bug, BMP Firmware, Regression

#1692 Fix: RISC-V missing quirks
  src/target/riscv_debug.c
Labels: Bug, HwIssue Mitigation

#1693 Fix: Tiva-C AP leak
  src/target/adiv5.c
Labels: Bug
