Repository blackmagic-debug/blackmagic, pull requests merged in 2023-04, with the labels that each got.

#1386 Fix: STM32F1 option bytes handling correctness
  src/target/stm32f1.c
Labels: Bug, HwIssue Mitigation

#1413 Fix: Tiva-C TM4C129 identification
  src/target/lmi.c
Labels: Bug, HwIssue Mitigation, Regression

#1415 Fix: LPC Flash registration
  src/target/lpc11xx.c
  src/target/lpc15xx.c
  src/target/lpc17xx.c
  src/target/lpc43xx.c
  src/target/lpc546xx.c
  src/target/lpc_common.c
  src/target/lpc_common.h
Labels: Bug, Regression

#1416 Feature: NTB component entry
  src/target/adiv5.c
Labels: Bug

#1422 Fix: SAM3Xxx Flash programming
  src/target/sam3x.c
Labels: Bug, HwIssue Mitigation

#1108 Fix: stm32l0/l1 is missing a mass erase implementation
  src/target/stm32l0.c
Labels: Bug, HwIssue Mitigation, BMP Firmware

#1431 Fix: BMDA's BMP remote protocol SWD cleanup
  src/platforms/hosted/remote_swdptap.c
Labels: BMD App

#1432 Fix: Semihosting
  src/gdb_hostio.c
  src/include/gdb_main.h
  src/main.c
Labels: Bug, GDB, Regression

#1438 crc32: Round up read length to a multiple of four
  src/crc32.c
Labels: Bug

#1189 Add some basic LPC55xx flashing support, tested only on LPC5504
  src/target/lpc55xx.c
Labels: New Target

#1439 Fix: Native platform pinout mistakes
  src/platforms/native/platform.c
  src/platforms/native/platform.h
Labels: Bug, BMP Firmware

#1441 Fix: cygwin compilation of BMDA
  src/command.c
  src/gdb_main.c
  src/platforms/hosted/bmp_hosted.h
  src/platforms/hosted/gdb_if.c
Labels: Bug, BMD App

#1445 target/lpc55xx: Fix memory leak in lpc55xx_add_flash
  src/target/lpc55xx.c
Labels: Bug

#1446 target: Fix out of bound array access in jtag_scan
  src/target/jtag_scan.c
Labels: Bug

#1453 blackpillv2/platform: add function platform_target_voltage_sense
  src/platforms/blackpillv2/platform.c
Labels: Bug

#1449 Fix: RP2040 Flash reliability
  src/target/rp.c
Labels: Bug, HwIssue Mitigation, Regression

#1456 Feature: LPC551x chip IDs
  src/target/lpc55xx.c
Labels: New Target

#1472 github: Switched to checkout@v3 in size-diff job of the build PR CI
  .github/workflows/build-pr.yml
Labels: Enhancement

#1479 make: Don't delete version.h in archives.
  src/Makefile
Labels: Bug, Enhancement

#1484 Fix git detection when using blackmagic as a submodule.
  src/Makefile
Labels: Bug, Regression

#1482 imxrt: use PRIu32 for debug print
  src/target/imxrt.c
Labels: Bug
