Repository blackmagic-debug/blackmagic, pull requests merged in 2023-09, with the labels that each got.

#1615 Feature: Soft start for target power on BMP
  src/platforms/native/platform.c
Labels: Enhancement, HwIssue Mitigation, BMP Firmware

#1617 mm32: support for mm32spin05
  src/target/stm32f1.c
Labels: New Target

#1621 Fix: Target power soft-start for older native hardware
  src/platforms/native/platform.c
Labels: Enhancement, BMP Firmware, NativeHardware

#1616 Feature: Add LED feedback for USB enumeration
  src/platforms/common/stm32/timing_stm32.c
  src/platforms/common/usb.c
  src/platforms/common/usb.h
Labels: Enhancement, BMP Firmware

#1625 rtt: fix hang when aux serial not read
  src/platforms/common/stm32/rtt_if.c
Labels: Bug, BMP Firmware

#1626 Fix: Cortex-A support
  src/target/cortexa.c
Labels: Bug, Regression

#1627 Feature: FTDI structure clarity & documentation
  src/platforms/hosted/ftdi_bmp.c
  src/platforms/hosted/ftdi_bmp.h
  src/platforms/hosted/ftdi_jtag.c
  src/platforms/hosted/ftdi_swd.c
Labels: Enhancement, BMD App, Documentation

#1628 Fix: Avoid a hang in scanning Cortex-A of STM32MP15x
  src/target/cortexa.c
Labels: Bug, HwIssue Mitigation, New Target

#1630 Fix: Cortex-A halt handling of OSLock becoming set between resumption and the next halt
  src/target/cortexa.c
Labels: Bug, HwIssue Mitigation
