Repository blackmagic-debug/blackmagic, pull requests merged in 2023-01, with the labels that each got.

#1352 rtt: correct enum type naming
  src/rtt.c
Labels: Enhancement

#1355 Fix: Target registers description crash
  src/target/target.c
Labels: Bug, Regression

#1369 hosted/cmsis_dap: Fixes CMSIS-DAP adapters connected with USB HID.
  src/platforms/hosted/cmsis_dap.c
Labels: Bug, BMD App

#1362 target: MindMotion MM32
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/cortexm.c
  src/target/cortexm.h
  src/target/stm32f1.c
  src/target/target_probe.c
  src/target/target_probe.h
Labels: New Target

#1339 stm32l4: add stm32wb1x parts detection.
  src/target/stm32l4.c
Labels: New Target

#1332 semihosting: output redirection to usb-uart on all platforms, except …
  src/platforms/hydrabus/platform.h
  src/platforms/launchpad-icdi/platform.h
  src/platforms/native/platform.h
  src/platforms/stlink/platform.h
  src/platforms/swlink/platform.h
  src/target/cortexm.c
  src/target/target.c
  src/target/target_internal.h
Labels: Enhancement, BMP Firmware

#1378 gdb_main: Handle continue with signal command
  src/gdb_main.c
Labels: Bug, Enhancement, GDB
