Repository blackmagic-debug/blackmagic, pull requests merged in 2023-10, with the labels that each got.

#1633 Fix: Added pinout documentation to the stlink platform
  src/platforms/stlink/README.md
Labels: Documentation, Foreign Host Board

#1634 mm32: typo in comment
  src/target/stm32f1.c
Labels: Documentation

#1636 Workaround for TM4C AP duplication
  src/target/adiv5.c
Labels: Bug, HwIssue Mitigation

#1641 Fix: BMDA AP access decoding
  src/platforms/hosted/platform.c
Labels: Bug, BMD App, Regression

#1648 Fix: platforms/common/stm32: fix for adc_start_conversion_direct not being defined for STM32F4
  src/platforms/common/stm32/timing_stm32.c
Labels: Bug, BMP Firmware, Foreign Host Board

#1645 Fix: platforms/blackpill-f4: invert state of SET_IDLE_STATE
  src/platforms/common/blackpill-f4/blackpill-f4.h
Labels: Bug, Foreign Host Board

#1637 Feature: add support for TM4C1294KCDT
  src/target/lmi.c
Labels: New Target, Documentation

#1647 Feature: platforms/blackpill-f4: define user button port and pin
  src/platforms/common/blackpill-f4/blackpill-f4.c
  src/platforms/common/blackpill-f4/blackpill-f4.h
  src/platforms/common/blackpill-f4/usbdfu.c
Labels: Enhancement, Foreign Host Board

#1651 misc: add nix-direnv integration
  .envrc
  .gitignore
Labels: Enhancement

#1660 Fix: BMDA SWD no_check routines
  src/platforms/hosted/platform.c
Labels: Bug, BMD App, Regression

#1662 samd: fix device id register masks
  src/target/samd.c
Labels: Bug

#1659 Feature: samd: Implemented support for the SAMC21 series
  src/target/samd.c
Labels: New Target
