Repository blackmagic-debug/blackmagic, pull requests merged in 2023-06, with the labels that each got.

#1503 target: GigaDevice GD32E50x
  src/target/stm32f1.c
Labels: New Target

#1505 actions: Updated PR workflow to use up to date arm compiler.
  .github/workflows/build-pr.yml
Labels: CI

#1511 cortexm: Avoid long division for non-hosted
  src/target/cortexm.c
Labels: Enhancement, BMP Firmware

#1512 Fix: Replace strtol with strtoul
  src/command.c
  src/gdb_packet.c
  src/target/stm32f1.c
Labels: Enhancement, BMP Firmware

#1513 Fix: Use reentrant strtok_r
  src/command.c
Labels: Enhancement

#1515 platforms/blackpill-f4: fix inverted tpwr command
  src/platforms/common/blackpill-f4/blackpill-f4.c
Labels: Bug, Foreign Host Board

#1517 Fix: ENABLE_DEBUG=1 build throws -Wunused-variable in imxrt.c
  src/target/imxrt.c
Labels: Bug, BMD App

#1521 target/stm32h7: fix checking result from bank erase while mass erasing
  src/target/stm32h7.c
Labels: Bug

#454 Fix: Connect-under-reset handling reliability
  src/target/cortexm.c
Labels: HwIssue Mitigation, BMP Firmware

#1522 Feature: Refactored LPC546xx device identification using a LUT
  src/target/lpc546xx.c
Labels: Enhancement

#1524 Invalid sector_num fixed for dfu erase stm32f4
  src/platforms/common/stm32/dfu_f4.c
Labels: Bug, Regression, Foreign Host Board
