Repository blackmagic-debug/blackmagic, pull requests merged in 2023-02, with the labels that each got.

#1271 Implement proper support for GD32F4 microcontrollers
  src/target/cortexm.c
  src/target/stm32f4.c
  src/target/target_probe.c
  src/target/target_probe.h
Labels: New Target

#1379 STM32L4, STM32WB: Clear OPTVERR before checking FLASH_SR_ERROR_MASK
  src/target/stm32l4.c
Labels: Bug, HwIssue Mitigation

#443 [WIP] ARMv7-A/R fixes needed to work with Cortex-R5
  src/target/cortexa.c
Labels: Enhancement, Draft, New Target

#1375 Fix: RTT code cleanup
  src/rtt.c
Labels: Enhancement

#1381 Fix: JEP-106 codes organisation
  src/target/adiv5.c
  src/target/adiv5.h
  src/target/cortexm.c
  src/target/jep106.h
  src/target/lpc11xx.c
Labels: Enhancement

#1382 Fix: GDB register API nomenclature and organisation
  src/target/cortexa.c
  src/target/cortexm.c
  src/target/gdb_reg.c
  src/target/gdb_reg.h
Labels: Enhancement

#1388 hosted/probe_info: don't use malloc.h
  src/platforms/hosted/probe_info.c
Labels: Bug, BMD App

#1392 bmp_libusb: Corrected include file path
  src/platforms/hosted/bmp_libusb.c
Labels: Bug, BMD App

#1393 exception.h: Added include guards for setjmp.h and setjmpex.h
  src/include/exception.h
Labels: Bug, BMD App

#1400 mm32: support for mm32f5277
  src/target/adiv5.c
  src/target/cortexm.c
  src/target/jep106.h
  src/target/stm32f1.c
Labels: New Target

#1405 gdb_main: don't reattach on connect
  src/gdb_main.c
Labels: Bug, GDB

#1407 ch32f1: Fixed hanging gdb load command for certain CH32F103C8T6 MCU's
  src/target/ch32f1.c
Labels: Bug, HwIssue Mitigation

#1408 stm32g0: Add identification for STM32C011 and STM32C031
  src/target/stm32g0.c
Labels: New Target

#1409 target/cortexm.c: Added missing probe call to sam3x_probe
  src/target/cortexm.c
Labels: Bug, Regression
