Repository blackmagic-debug/blackmagic, pull requests merged in 2024-06, with the labels that each got.

#1832 Fix UART TX and NRST pin conflict on stlink clones with SWIM_AS_UART
  cross-file/stlink.ini
  meson_options.txt
  src/platforms/stlink/Makefile.inc
  src/platforms/stlink/README.md
  src/platforms/stlink/meson.build
  src/platforms/stlink/platform.c
  src/platforms/stlink/platform.h
Labels: Bug, Foreign Host Board

#1843 Fix meson BMPBootloader on blackpill-f4
  src/platforms/common/blackpill-f4/Makefile.inc
  src/platforms/common/blackpill-f4/blackpill-f4.c
  src/platforms/common/blackpill-f4/meson.build
Labels: Bug, Foreign Host Board, Build system

#1848 Fix: Ensure F-packet replies from gdb are reliably detected
  src/target/semihosting.c
Labels: Bug, Regression

#1847 Feature: Add support for SYS_ELAPSED/SYS_TICKFREQ as milliseconds
  src/target/semihosting.c
Labels: Bug, Enhancement

#1849 meson: add C++ compiler entry to the default cross files
  cross-file/96b_carbon.ini
  cross-file/blackpill-f401cc.ini
  cross-file/blackpill-f401ce.ini
  cross-file/blackpill-f411ce.ini
  cross-file/bluepill.ini
  cross-file/f072.ini
  cross-file/f3.ini
  cross-file/f4discovery.ini
  cross-file/hydrabus.ini
  cross-file/launchpad-icdi.ini
  cross-file/native.ini
  cross-file/stlink.ini
  cross-file/stlinkv3.ini
  cross-file/swlink.ini
Labels: Enhancement, Build system
