Repository blackmagic-debug/blackmagic, pull requests merged in 2024-12, with the labels that each got.

#2008 Cortex-M: Temptative fix for watchpoints so they work on ARMv8-M cores (eg Cortex-M33)
  src/target/cortexm.c
  src/target/cortexm.h
Labels: Bug

#2011 cortexar: fix typo in cortexar_check_error
  src/target/cortexar.c
Labels: Bug

#2012 cortexar: halt core in cortexar_mem_write
  src/target/cortexar.c
Labels: Bug

#2021 gdb_packet: add missing <string.h> include
  src/include/gdb_packet.h
Labels: Bug

#2025 ctxlink/wifi_server: Fix variable names when debug is enabled.
  src/platforms/ctxlink/WiFi_Server.c
Labels: Bug, BMP Firmware, Foreign Host Board

#2024 gdb_packet: allow for external packet buffer
  src/gdb_packet.c
Labels: Bug, GDB, Foreign Host Board

#2005 Fix: Shrink SRAM sizes of STM32F0
  src/target/stm32f1.c
Labels: Bug

#2032 Fix AT32F405 flash size/map
  src/target/at32f43x.c
Labels: Bug

#2031 ctxlink/wifi_server: Change winc1500 power mode to manual.
  src/platforms/ctxlink/WiFi_Server.c
Labels: Enhancement, HwIssue Mitigation, Foreign Host Board

#2030 ctxlink/platform: Add debug output control to platform.
  src/platforms/ctxlink/platform.h
Labels: Bug, Enhancement, BMP Firmware, Foreign Host Board
