Repository blackmagic-debug/blackmagic, pull requests merged in 2024-10, with the labels that each got.

#1945 Feature: tri-state SWDIO, SWCLK on unbuffered platforms
  src/platforms/stlinkv3/platform.c
  src/platforms/stlinkv3/platform.h
Labels: Enhancement, Foreign Host Board

#1947 stm32l4: Added option bytes support for the STM32WBxx series (this ha…
  src/target/stm32l4.c
Labels: Enhancement

#1951 Fix: BMDA version command output
  src/command.c
  src/platforms/hosted/platform.c
  src/platforms/hosted/platform.h
Labels: Bug, Enhancement, GDB, BMD App

#1952 Fix: STM32L4/L5/U5/G4/WL/WB family identification
  src/target/stm32l4.c
Labels: Bug

#1961 meson: Added a script to build all the existing cross targets.
  scripts/meson-build-all.sh
Labels: Enhancement

#1964 meson: Disabled some of the default targets to make the code fit again.
  cross-file/f072.ini
  cross-file/native.ini
  cross-file/stlink.ini
Labels: BMP Firmware, Build system

#1959 ARM:Add Jtag to Dormant sequence in case the target has both jtag and swd
  src/target/adiv5_internal.h
  src/target/adiv5_swd.c
Labels: Bug, New Target

#1973 hosted: #include "general.h" before system headers
  src/platforms/hosted/serial_unix.c
Labels: Bug, BMD App

#1974 Fix `hosted/cli.c`, minor implicit fallthrough
  src/platforms/hosted/cli.c
Labels: Bug, BMD App

#1949 Feature: Add support for Arterytek MCU AT32F405, F402
  src/target/at32f43x.c
Labels: New Target

#1976 remote: provide correct 3-byte buffer to `hexify()`
  src/remote.c
Labels: Bug, BMP Firmware

#1977 miscellaneus RTT fixes
  src/include/rtt.h
  src/rtt.c
Labels: Bug

#1983 fix/ctxlink/platform
  src/platforms/ctxlink/platform.c
Labels: Bug, Foreign Host Board
