Repository blackmagic-debug/blackmagic, pull requests merged in 2024-03, with the labels that each got.

#1776 Fix dual stack listening
  src/platforms/hosted/gdb_if.c
Labels: Bug, Enhancement, BMD App

#1786 target/nxp: Re-enable ke04 support.
  src/target/cortexm.c
Labels: Bug

#1789 Fix: 1 typo
  src/target/cortexm.h
Labels: Enhancement
