Repository blackmagic-debug/blackmagic, pull requests merged in 2024-02, with the labels that each got.

#1759 riscv: make the debugger stop on ebreak
  src/target/riscv_debug.c
Labels: Bug, Enhancement

#1718 Fix: Declare smaller timeouts in F1 DFU to speed up probe upgrades
  src/platforms/common/stm32/dfu_f1.c
Labels: Enhancement, BMP Firmware

#1761 fix: Fixed typo in meson.build for gcc warning option
  meson.build
Labels: Bug, Build system

#1763 s32k3xx: fix debug logging format
  src/target/s32k3xx.c
Labels: Bug

#1766 riscv : add basic single precision hw float support
  src/target/riscv32.c
  src/target/riscv_debug.c
  src/target/riscv_debug.h
Labels: Enhancement

#1771 readme: add note about PowerShell command line options
  README.md
Labels: Documentation, Build system
