Repository blackmagic-debug/blackmagic, pull requests merged in 2024-07, with the labels that each got.

#1854 Fix stlinkv3 platform bits
  src/platforms/stlinkv3/README.md
  src/platforms/stlinkv3/platform.c
Labels: Bug, Enhancement, Foreign Host Board

#1856 Fix gdb idling too much on DWC
  src/platforms/common/stm32/gdb_if.c
Labels: Enhancement, BMP Firmware, Foreign Host Board

#1857 Fix: Guard the CH579 driver in Makefile builds for parity with meson (opt-in)
  src/Makefile
  src/platforms/hosted/Makefile.inc
Labels: Enhancement, Build system

#1852 Feature: AT32F435/437 Option Bytes support
  src/target/at32f43x.c
Labels: Enhancement

#1859 Fix: Update meson targets in cross-files for bigger platforms
  cross-file/96b_carbon.ini
  cross-file/blackpill-f401cc.ini
  cross-file/blackpill-f401ce.ini
  cross-file/blackpill-f411ce.ini
  cross-file/f3.ini
  cross-file/f4discovery.ini
  cross-file/hydrabus.ini
  cross-file/launchpad-icdi.ini
  cross-file/stlinkv3.ini
Labels: Enhancement, Build system

#1860 Fix: STM32 UID decoder: avoid displaying non-printable bytes
  src/target/stm32_common.c
Labels: Bug, Enhancement

#1861 Fix `blackpill-f4` requiring a reset after exiting ST MaskROM
  src/platforms/common/blackpill-f4/blackpill-f4.c
  src/platforms/common/blackpill-f4/usbdfu.c
Labels: Bug, Foreign Host Board

#1863 Fix: Unify help messages for Unique ID with STM32
  src/target/efm32.c
  src/target/nrf51.c
  src/target/renesas_ra.c
Labels: Enhancement

#1714 common/swdptap: make SWD timing more consistent
  src/platforms/common/swdptap.c
Labels: Enhancement, BMP Firmware

#1870 Fix: Use unbuffered stdout on Windows
  src/platforms/hosted/platform.c
Labels: Bug, Enhancement, BMD App

#1872 ctxlink: Fix bootloader related readme and optimize code
  src/platforms/ctxlink/README.md
  src/platforms/ctxlink/platform.c
Labels: Bug, Enhancement, Documentation, Foreign Host Board

#1873 Fix diagnostic logs on CDC-ACM of STLINK/V3
  src/platforms/common/usb_serial.c
Labels: Bug, Enhancement, BMP Firmware, Foreign Host Board

#1875 Fix: CMSIS-DAP SWD data shift UB
  src/platforms/hosted/dap_swd.c
Labels: Bug, BMD App

#1877 Correct USB UART DMA configuration
  src/platforms/ctxlink/platform.h
Labels: Bug, Foreign Host Board

#1876 Fix: Opt out of libgcc unwinder pulled by >=newlib-4.3.0
  src/platforms/common/syscalls.c
Labels: Bug, BMP Firmware

#1881 Feature: Add platform-specific commands support
  src/command.c
Labels: Enhancement, Foreign Host Board
