Repository blackmagic-debug/blackmagic, pull requests merged in 2024-09, with the labels that each got.

#1917 blackpill-f4: Fix error in comment describing the timer used for traceswo
  src/platforms/common/blackpill-f4/blackpill-f4.h
Labels: Bug, Documentation, Foreign Host Board

#1906 Feature: expand docs for `blackpill-f4`
  src/platforms/common/blackpill-f4/README.md
Labels: Documentation, Foreign Host Board

#1916 Fix: cortexar: BMP/gdb connection hang on run
  src/target/cortexar.c
Labels: Bug, GDB

#1869 Feature: watchdog & sleep management on ArteryTek AT32F43x
  src/target/at32f43x.c
Labels: Bug, Enhancement

#1926 Fix: AT32F435/437: Correct typos in WFI/WDT handling
  src/target/at32f43x.c
Labels: Bug

#1925 Fix: Broken CMSIS-DAP SWD sequence
  src/platforms/hosted/dap.h
  src/platforms/hosted/dap_command.c
Labels: Bug, BMD App

#1936 hosted/serial_win: Print auxiliary serial COM port
  src/platforms/hosted/serial_win.c
Labels: Enhancement, BMD App

#1940 cortexm: allow updating demcr from outside
  src/target/cortexm.c
  src/target/cortexm.h
Labels: Enhancement

#1943 swo: gate usb-specific defines behind `!defined(NO_LIBOPENCM3)`
  src/platforms/common/swo.h
Labels: Enhancement, BMP Firmware

#1798 Feature: Add to `blackpill-f4` an `swlink`-like alternative pinout 2
  src/platforms/common/blackpill-f4/blackpill-f4.c
  src/platforms/common/blackpill-f4/blackpill-f4.h
Labels: Foreign Host Board
