Repository blackmagic-debug/blackmagic, pull requests merged in 2024-04, with the labels that each got.

#1792 Restore .clang-tidy config to valid YAML
  .clang-tidy
Labels: Bug, Regression, Build system

#1796 Fix: Xilinx Artix-7 IR quirk for 6-bit IR found on XC7A200T
  src/target/jtag_devs.c
Labels: Enhancement, HwIssue Mitigation

#1797 Added support for kinetis MK20DX256 chip
  src/target/kinetis.c
Labels: New Target

#1804 Fix remaining length calculation for 'X' 'M' and 'vFlashWrite'
  src/gdb_main.c
Labels: Bug, GDB, Regression

#1802 Fix STLINK/V2 operation with multi-AP chips and block reads
  src/platforms/hosted/stlinkv2.c
  src/platforms/hosted/stlinkv2_protocol.h
Labels: Bug, BMD App, Regression

#1807 stm32l4: Fix flash for STM32U5xx
  src/target/stm32l4.c
Labels: Bug
