Repository blackmagic-debug/blackmagic, pull requests merged in 2024-08, with the labels that each got.

#1878 Feature: Adapt traceswoasync (F103) to F4 API
  src/platforms/common/stm32/traceswoasync.c
Labels: Enhancement, BMP Firmware, Foreign Host Board

#1879 Feature: Switch `blackpill-f4` to traceswoasync.c driver
  src/platforms/common/blackpill-f4/Makefile.inc
  src/platforms/common/blackpill-f4/blackpill-f4.h
  src/platforms/common/blackpill-f4/meson.build
Labels: Enhancement, BMP Firmware, Foreign Host Board

#1885 Fix: Fixed platform_cmd_list extern declaration in command.c
  src/command.c
Labels: Bug

#1888 stm32: fix formatting for DEBUG_TARGET on esp32
  src/target/stm32h7.c
  src/target/stm32mp15.c
Labels: Bug

#1889 target: stm32h7: print hex instead of decimal
  src/target/stm32h7.c
Labels: Bug

#1893 cortexar: fixed CPSR mapping for GDB
  src/target/cortexar.c
Labels: Bug, Enhancement

#1897 Fix addresses on STM32H5 (DBGMCU, SRAM alias)
  src/target/stm32h5.c
Labels: Bug

#1898 Feature: added "Platform commands:" message in cmd_help
  src/command.c
Labels: Enhancement

#1895 Fix: STM32L4 DBGMCU handling
  src/target/stm32l4.c
Labels: Bug, Regression

#1828 Fix: -Wformat for tc_printf
  src/target/ch579.c
  src/target/efm32.c
  src/target/lpc546xx.c
  src/target/nrf51.c
  src/target/renesas_ra.c
  src/target/sam3x.c
  src/target/samd.c
  src/target/samx5x.c
  src/target/semihosting.c
  src/target/stm32f1.c
  src/target/stm32g0.c
  src/target/stm32h7.c
  src/target/stm32l0.c
  src/target/stm32l4.c
  src/target/target_internal.h
Labels: Enhancement

#1900 Fix: s32k3xx: Remove the single assert
  src/target/s32k3xx.c
Labels: Enhancement, Regression

#1903 Fix: Enable parallel make workers on GH Actions CI
  .github/workflows/build-pr.yml
Labels: Enhancement, CI

#1904 target_flash: Prevent NULL dereference when detached from targets
  src/target/target_flash.c
Labels: Bug, GDB

#1896 Fix: renesas_rz: autodetect RAM size based on RAM reads
  src/target/renesas_rz.c
Labels: Bug

#1914 ctxlink/platform: Fix plarform_target_voltage_return
  src/platforms/ctxlink/platform.c
Labels: Bug, BMP Firmware, Regression, Foreign Host Board
