Repository blackmagic-debug/blackmagic, pull requests merged in 2024-11, with the labels that each got.

#1987 Feature: Add support for APB2/APB3 configuration
  src/target/adi.c
Labels: Bug, Enhancement

#1980 Fix: `tdi_low_reset` crash
  src/command.c
Labels: Bug

#1991 Update_blackpill_readme
  src/platforms/common/blackpill-f4/README.md
Labels: Documentation, Foreign Host Board

#1993 fix/ctxlink/readme: Update ctxlink readme to reflect the recent build system changes
  src/platforms/ctxlink/README.md
Labels: Documentation, Foreign Host Board

#1994 Revert "cortexar: Read CPUID when the core is powered"
  src/target/cortexar.c
Labels: Bug, Regression

#1803 Feature: Arterytek option bytes and more part IDs
  src/target/stm32f1.c
Labels: Enhancement, New Target

#1995 stm32f1: use PRIx32 macro for debug log
  src/target/stm32f1.c
Labels: Bug

#1996 Fix: AT32F43x cleanup
  src/target/at32f43x.c
  src/target/meson.build
Labels: Enhancement

#2002 Fix: mspm0: Remove a couple asserts
  src/target/mspm0.c
Labels: Enhancement

#1990 stlink: add config for the ISOL variant
  cross-file/stlink.ini
  meson_options.txt
  src/platforms/stlink/meson.build
Labels: Enhancement, Foreign Host Board

#1767 riscv : fix the inverted logc interrupt-are-disabled-while-single-ste…
  src/target/riscv_debug.c
Labels: Bug

#2004 Fix: MSPM0 cleanup
  src/target/mspm0.c
Labels: Enhancement

#2007 ctxlink/wifi: fix the speed issues with the Wi-Fi interface
  src/platforms/ctxlink/WiFi_Server.c
  src/platforms/ctxlink/platform.c
  src/platforms/ctxlink/platform.h
Labels: Bug, Foreign Host Board
