Repository blackmagic-debug/blackmagic, pull requests merged in 2024-05, with the labels that each got.

#1818 Fix: Simplify debug log guard in imxrt.c
  src/target/imxrt.c
Labels: Enhancement

#1814 Feature: STM32F410 support
  src/target/stm32f4.c
Labels: New Target

#1820 Fix: Replace `sprintf()` calls remaining in firmware with `snprintf()`
  src/target/efm32.c
  src/target/sam3x.c
  src/target/stm32l0.c
Labels: Enhancement

#1822 ci: Fix deployment of GCC < 14 under macOS
  .github/workflows/build-pr.yml
Labels: CI, Build system

#1821 Please report unknown device with Designer 0x8055 Part ID 0x29b - Add support for another STM32F01 clone
  src/target/adiv5.c
  src/target/jep106.h
Labels: HwIssue Mitigation, New Target

#1824 Fix: macOS Homebrew CI
  .github/workflows/build-pr.yml
Labels: Bug, CI

#1829 Feature: GD32F405 support
  src/target/stm32f4.c
Labels: New Target

#1831 hosted/remote: Fix platform_nrst_get_val spell error
  src/platforms/hosted/bmp_remote.c
Labels: Bug, BMD App

#1834 Fix checks of `vasprintf` in gdb_packet.c
  src/gdb_packet.c
Labels: Bug

#1835 adiv5: Fix ADIV5_DP_DPIDR_REVISION_MASK macro mismatch
  src/target/adiv5.h
Labels: Bug
