Repository blackmagic-debug/blackmagic, pull requests merged in 2024-01, with the labels that each got.

#1707 native/platform: fix DFU detach
  src/platforms/native/platform.c
Labels: Bug, BMP Firmware

#1713 Fix: Replace attribute alias in CRC32
  src/crc32.c
Labels: Bug, Regression

#1710 Feature: Increase SRAM layout detail for STM32H7 chip variants
  src/target/stm32h7.c
Labels: Enhancement

#1716 Feature: Space-efficient 12-symbol serialno generation
  src/platforms/common/stm32/serialno.c
Labels: Enhancement, BMP Firmware, Foreign Host Board

#1721 Fix: Momentary bandgap reference read glitch
  src/platforms/common/stm32/timing_stm32.c
Labels: Bug, HwIssue Mitigation, NativeHardware

#1727 pre-commit: use check-accidental-assignment v0.3 which handles single…
  .pre-commit-config.yaml
Labels: Bug, CI, Build system

#1728 Fix: Renesas build error
  src/target/meson.build
Labels: Bug, BMD App, Build system

#1734 target: properly fix weak aliasing of probe NOPs on macOS
  src/target/target_probe.c
Labels: Bug, BMD App

#1735 meson: add build target feedback to summary
  meson.build
Labels: Enhancement, Build system

#1736 common: fix UB in some bit shifts
  src/platforms/common/stm32/gpio.h
  src/platforms/common/swdptap.c
Labels: Bug, Enhancement, BMP Firmware

#1740 Fix: BMDA Windows serial timeouts
  src/platforms/hosted/serial_win.c
Labels: Bug, BMD App

#1720 Feature: Support stlink v2 isol variant
  src/platforms/stlink/Makefile.inc
  src/platforms/stlink/platform.c
  src/platforms/stlink/platform.h
  src/platforms/stlink/stlink_common.c
Labels: Foreign Host Board

#1744 pre-commit hooks fixups
  .pre-commit-config.yaml
Labels: Enhancement, CI, Build system

#1745 Fix: use v0.3.1 perigoso/pre-commit-hooks
  .pre-commit-config.yaml
Labels: CI, Build system

#1747 target: Adjusted RZ/A1LU to RZ/A1 target name
  src/target/renesas_rz.c
Labels: Enhancement, New Target

#1746 stlink: replace odr register for the isol variant
  src/platforms/stlink/platform.h
Labels: Enhancement, Foreign Host Board

#1739 Fix revision-reporting command for STM32MP15x
  src/target/stm32mp15.c
Labels: Bug, Regression

#1755 Fix `stm32h7_cmd_rev`
  src/target/stm32h7.c
Labels: Bug, Enhancement
