Repository blackmagic-debug/blackmagic, pull requests merged in 2025-07, with the labels that each got.

#2130 Fix: Config macro errors
  src/remote.c
Labels: Bug, BMP Firmware

#2096 Fix: minor deduplication in Puya driver
  src/target/puya.c
Labels: Enhancement

#2131 Feature: STM32H523/H533 support
  src/target/stm32h5.c
Labels: New Target

#2126 cortexm: Add v8m secure fault to vector_catch
  src/target/cortexm.c
Labels: Enhancement

#2070 Feature: samd: Add support for PIC32CM MC Family
  src/target/samd.c
Labels: New Target
