Repository blackmagic-debug/blackmagic, pull requests merged in 2025-02, with the labels that each got.

#2069 [efm32_probe] Fix detection of DI v2
  src/target/efm32.c
Labels: Bug, Regression

#2068 blackpill-f4: Enable internal weak pull-up on nRST, simplify set_val
  src/platforms/common/blackpill-f4/blackpill-f4.c
Labels: Bug, HwIssue Mitigation, Foreign Host Board

#2073 blackpill-f4: change slew speed frequency cutoff to 3 MHz
  src/platforms/common/blackpill-f4/blackpill-f4.c
Labels: HwIssue Mitigation, Foreign Host Board
