Repository blackmagic-debug/blackmagic, pull requests merged in 2025-01, with the labels that each got.

#2035 Fix: MCU-Link CMSIS-DAP version handling issues
  src/platforms/hosted/cmsis_dap.c
Labels: Bug, HwIssue Mitigation, BMD App

#2039 Fix: Nightly build version strings
  .github/workflows/build-and-upload.yml
Labels: Bug, CI

#2041 Fix: unexpected E02 from gdb m-packets
  src/gdb_main.c
Labels: Bug, GDB, Regression

#2043 Fix: Rename RISC-V machine scratch CSR
  src/target/riscv_debug.c
Labels: Bug

#2049 Fix: Contribution guidelines
  CONTRIBUTING.md
Labels: Bug, Documentation

#2053 Fix: Treat GD32E508 in JTAG transport as ADIv5
  src/target/adiv5.h
  src/target/adiv5_jtag.c
Labels: Bug, Regression

#2054 Fix: adiv5/6 JTAG version handling
  src/target/adiv5.h
  src/target/adiv5_jtag.c
Labels: Bug, Regression

#1649 Feature: platforms/blackpill-f4: only setup LED_BOOTLOADER once
  src/platforms/common/blackpill-f4/blackpill-f4.c
Labels: Bug, Foreign Host Board

#1913 Fix: imxrt: Cortex-M4 core detection for RT1176
  src/target/imxrt.c
Labels: Bug

#2056 Add option to compile blackpill-f4* with SHIELD option, using meson
  meson_options.txt
  src/platforms/common/blackpill-f4/meson.build
Labels: Bug, Regression, Build system

#2066 blackpill/platform: Correct the condiitonal compilation symbol to initialize the bootloader LED pin.
  src/platforms/common/blackpill-f4/blackpill-f4.c
Labels: Bug, BMP Firmware, Foreign Host Board

#2067 Blackpill/readme: Update to describe need for "on_carrier_board" option
  src/platforms/common/blackpill-f4/README.md
Labels: Bug, Documentation, Foreign Host Board
