Repository blackmagic-debug/blackmagic, pull requests merged in 2025-03, with the labels that each got.

#2078 misc: Add bootloader build instructions to README.md
  README.md
Labels: Enhancement, Documentation

#2079 Fix BMD Bootloader to handle DFU_DETACH requests explicitly
  src/platforms/common/stm32/dfucore.c
Labels: Enhancement, BMP Firmware

#2095 cortemx: use a global define to make sure we allocate enough room for registers
  src/target/cortexm.c
Labels: Bug

#2075 Fix: Declare correct RAM sizes for STM32F7
  src/target/stm32f4.c
Labels: Bug

#2077 Fix STM32F7 ITCM Flash alias map
  src/target/stm32f4.c
Labels: Bug

#2100 native/platform: Fix and add documentation for TMS_DIR and TCK_DIR on native
  src/platforms/native/platform.h
Labels: Enhancement, BMP Firmware, NativeHardware
